### ISSUE TITLE
how can i run autoprefixer in teiminal

### ISSUE THREAD

**Issue by zhiqiang21** [Ioannis-Kapoulas/vim-autoprefixer#1]
when i run autoprefixer in terminal ,it say command not find

**Comment by Ioannis-Kapoulas** [comment]
You can use the postcss-cli to run Autoprefixer from CLI:

npm install --global postcss-cli autoprefixer
postcss --use autoprefixer *.css -d build/
See postcss -h for help.

**Comment by Ioannis-Kapoulas** [comment]
vim-autoprefixer now works with the new postcss/autoprefixer-cli
