### ISSUE TITLE
Autoprefixer has deprecated cli

### ISSUE THREAD

**Issue by steadystatic** [Ioannis-Kapoulas/vim-autoprefixer#2]
The PostCSS folks have deprecated the `autoprefixer` cli tool.

Please update the instructions to reflect: npm install --global postcss-cli autoprefixer

There could be a better method, but I just added this to my ~/.zshenv (I use ZSH, so if you use Bash or otherwise take note) so Vim could pick up on it:

alias autoprefixer="postcss --use autoprefixer"

**Comment by Ioannis-Kapoulas** [comment]
vim-autoprefixer now works with the new `postcss-cli`. 
The instructions have been updated.
